<template>
  <v-dialog v-model="dialog" persistent max-width="700" scrollable>
    <v-card flat class="white rounded-xl">
      <general-card-dialog-header
        name="Voucher"
        @close="onEmitClose"
        :loading="state.isLoading"
      />

      <v-card-text class="pa-6">
        <v-form v-model="state.isValid" ref="form">
          <template v-if="isRetailType">
            <general-form-autocomplete
              v-model="form.retailId"
              :items="partners"
              item-text="name"
              item-value="id"
              label="Partner"
              outlined
              required
              bold
              :rules="[required]"
              @keydown="onSelectPartners"
            />
          </template>

          <template v-if="!isRetailType">
            <general-form-autocomplete
              v-model="form.searchMerchantCategories"
              v-if="!isEdited"
              :items="items.merchantCategories"
              label="Merchant Categories"
              item-text="name"
              return-object
              outlined
              required
              bold
              hide-details
              @keydown="onSearchMerchantCategories"
              @change="onSelecteMerchantCategories"
            />

            <general-form-text-field
              v-if="!isEdited"
              hide-details="auto"
              dense
              class="hide-input mb-4"
              v-model="form.selectedMerchantCategories"
              :rules="[arrayRule]"
            />

            <p class="h6--xsmall label--text mb-4" v-if="isEdited">Merchants</p>

            <v-row dense>
              <v-col
                class="pa-0"
                cols="auto"
                v-for="(category, index) in form.selectedMerchantCategories"
                :key="index"
              >
                <v-chip
                  class="ma-2"
                  :close="!isEdited"
                  @click:close="onRemoveMerchantCategories(index)"
                >
                  {{ category.name }}
                </v-chip>
              </v-col>
            </v-row>

            <v-divider class="my-5 dark lighten-3" />

            <general-form-autocomplete
              v-if="!isEdited"
              label="Kota"
              bold
              required
              v-model="form.searchRegencies"
              className="text-capitalize"
              outlined
              hide-details
              :items="items.regencies"
              item-text="name"
              return-object
              :loading="state.loadingRegencies"
              @keydown="onFetchRegencies"
              @change="onSelectRegency"
            />

            <general-form-text-field
              v-if="!isEdited"
              hide-details="auto"
              dense
              class="hide-input mb-4"
              v-model="form.selectedRegencies"
              :rules="[arrayRule]"
            />

            <p class="h6--xsmall label--text mb-4" v-if="isEdited">Locations</p>
            <v-row dense>
              <v-col
                class="pa-0"
                cols="auto"
                v-for="(category, index) in form.selectedRegencies"
                :key="index"
              >
                <v-chip
                  class="ma-2"
                  :close="!isEdited"
                  @click:close="onRemoveCity(index)"
                >
                  {{ category.name }}
                </v-chip>
              </v-col>
            </v-row>

            <v-divider class="mb-8 mt-5 dark lighten-3" />
          </template>

          <template v-if="!isEdited">
            <template v-if="!isRetailType">
              <p class="h6--xsmall label-text">Voucher</p>
              <v-radio-group
                row
                hide-details
                v-model="state.isAutoGeneratedVoucher"
              >
                <v-radio
                  v-for="i in 2"
                  :key="i"
                  :ripple="false"
                  :value="i === 2"
                  class="mb-6"
                >
                  <template v-slot:label>
                    <span class="text--default">
                      {{ i === 1 ? "Upload" : "Auto Generate" }}</span
                    >
                  </template>
                </v-radio>
              </v-radio-group>
            </template>

            <template v-if="!state.isAutoGeneratedVoucher">
              <general-form-file
                :acceptFile="['.csv', 'xls', '.xlsx']"
                class="mb"
                :required="[state.isAutoGeneratedVoucher ? required : true]"
                bold
                label="Voucher File"
                :form="form"
              />
            </template>

            <template v-if="state.isAutoGeneratedVoucher">
              <v-row dense>
                <v-col cols="12" md="3">
                  <general-form-text-field
                    required
                    v-model="generateOptions.prefix"
                    label="Prefix"
                    outlined
                    bold
                    :rules="[state.isAutoGeneratedVoucher ? required : true]"
                  />
                </v-col>
                <v-col cols="12" md="3">
                  <general-form-text-field
                    required
                    v-model="generateOptions.postfix"
                    label="Postfix"
                    outlined
                    bold
                    :rules="[state.isAutoGeneratedVoucher ? required : true]"
                  />
                </v-col>
                <v-col cols="12" md="3">
                  <general-form-text-field
                    required
                    v-model="generateOptions.length"
                    label="Length"
                    outlined
                    bold
                    :rules="[state.isAutoGeneratedVoucher ? required : true]"
                    @keypress="onDigits"
                  />
                </v-col>
                <v-col cols="12" md="3">
                  <general-form-text-field
                    required
                    v-model="generateOptions.count"
                    label="Count"
                    outlined
                    bold
                    :rules="[state.isAutoGeneratedVoucher ? required : true]"
                    @keypress="onDigits"
                  />
                </v-col>
              </v-row>
            </template>
          </template>

          <div class="mb-8 mt-2">
            <div class="d-flex align-center mb-2">
              <p class="h6--xsmall label-text">Expired Date</p>
              <p class="h6--xsmall text-capitalize label-text ml-1 error--text">
                *
              </p>
            </div>

            <div class="d-flex">
              <general-form-date-picker
                v-model="form.date"
                :dateValue="form.date"
                :min="minDate"
                class="mr-2"
                outlined
                label="Date"
                :rules="[required]"
              />

              <general-form-timepicker
                v-model="form.time"
                label="Time"
                format="HH:mm:ss"
                placeholder="Waktu (WIB)"
                :rules="[required]"
              />
            </div>
          </div>

          <general-form-autocomplete
            v-model="form.productId"
            :items="setProduct"
            item-text="name"
            item-value="id"
            label="Product"
            outlined
            required
            bold
            :rules="[required]"
          />

          <general-form-text-field
            required
            v-model="form.limit"
            label="Limit per User"
            outlined
            bold
            :rules="[required]"
            @keypress="onDigits"
          />

          <general-form-rich-editor
            required
            v-model="form.usageInstruction"
            label="Usage Instruction Steps"
            outlined
            bold
            :rules="[required]"
          />
          <general-form-text-field
            hide-details="auto"
            dense
            class="hide-input mt-2 mb-4"
            v-model="form.usageInstruction"
            :rules="[required]"
          />

          <div class="d-flex justify-end mt-8">
            <v-btn
              class="secondary lighten-5 text-capitalize ml-2 h7--xxsmall"
              depressed
              :loading="state.isLoading"
              @click="onSubmit()"
            >
              Submit
            </v-btn>
          </div>
        </v-form>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script>
import rules from "@/mixins/rules";
import utils from "@/mixins/utils";
import pipe from "@/mixins/pipe";
import debounce from "lodash/debounce";

export default {
  mixins: [rules, utils, pipe],
  props: {
    item: Object,
    dialog: Boolean,
    partners: Array,
    products: Array,
    isEdited: Boolean,
    isRetailType: Boolean,
  },

  data: () => ({
    items: {
      merchantCategories: [],
      regencies: [],
    },
    state: {
      isAutoGeneratedVoucher: false,
      isValid: false,
      isLoading: false,
      loadingFetchMerchantCategories: false,
      loadingRegencies: false,
    },
    form: {
      searchMerchantCategories: "",
      searchRegencies: "",
      merchantCities: [],
      retailId: null,
      productId: {},
      expiredDate: "",
      limit: null,
      usageInstruction: null,
      file: null,
      selectedMerchantCategories: [],
      selectedRegencies: [],
      date: "",
      time: {
        hh: "",
        mm: "",
        ss: "",
      },
    },
    generateOptions: {
      count: "",
      length: "",
      prefix: "",
      postfix: "",
    },
  }),

  computed: {
    setProduct() {
      if (this.products?.length > 0) {
        return this.products?.map((x) => {
          return { ...x.product };
        });
      }
    },

    minDate() {
      let date = new Date();
      return this.$dayjs(date).format("YYYY-MM-DD");
    },
  },

  methods: {
    onFetchRegencies: debounce(function (val) {
      const keyword = val.target._value;
      this.getRegencies(keyword);
    }, 500),

    async getRegencies(val) {
      this.state.loadingRegencies = true;
      let payload = {
        keyword: val,
        limit: 0,
        sort: "name",
      };

      let res = await this.$api.general.regencies(payload);

      if (res.success) {
        this.items.regencies = res.data.list;
      }

      this.state.loadingRegencies = false;
    },

    onRemoveMerchantCategories(index) {
      this.form.selectedMerchantCategories?.splice(index, 1);
      this.$forceUpdate();
    },

    onRemoveCity(index) {
      this.form.selectedRegencies?.splice(index, 1);
      this.$forceUpdate();
    },

    onSelecteMerchantCategories(val) {
      const index = this.form.selectedMerchantCategories?.findIndex((x) => {
        return x.id === val?.id;
      });

      if (index < 0 && val) {
        this.form.selectedMerchantCategories.push(val);
      }
    },

    onSelectRegency(val) {
      const index = this.form.selectedRegencies?.findIndex((x) => {
        return x.id === val?.id;
      });

      if (index < 0 && val) {
        this.form.selectedRegencies.push(val);
      }
    },

    async getMerchantCategories(val) {
      this.state.loadingFetchMerchantCategories = true;
      const payload = {
        keyword: val,
        page: 1,
        limit: 3,
        sort: "name",
      };
      const res = await this.$api.merchants.category.getList(payload);

      if (res.success) {
        this.items.merchantCategories = res.data.list;
      }

      if (!res.success) {
        this.setFailedAlert(res);
      }

      this.state.loadingFetchMerchantCategories = false;
    },

    onSelectPartners: debounce(function (val) {
      const keyword = val.target._value;
      this.$emit("fetch:partners", keyword);
    }, 500),

    onSearchMerchantCategories: debounce(function (val) {
      const keyword = val.target._value;
      this.getMerchantCategories(keyword);
    }, 500),

    onEmitClose() {
      this.$emit("on:close");
    },

    async onSubmit() {
      const valid = await this.validate(this.state.isValid);
      const campaignId = this.$route.params.slug;

      if (!valid) return;
      this.state.isLoading = true;

      if (!this.isRetailType) delete this.form.retailId;

      const hours = this.form.time.hh || 23;
      const minutes = this.form.time.mm || 59;
      const seconds = this.form.time.ss || 59;

      const dateInstance = this.$dayjs(this.form.date)
        .hour(hours)
        .minute(minutes)
        .second(seconds);

      let payload = {
        file: this.form.file,
        retailId: this.form.retailId,
        productId: this.form.productId,
        expiredDate: dateInstance?.toISOString(),
        limit: this.toInt(this.form.limit),
        usageInstruction: this.form.usageInstruction,
        id: campaignId,
      };

      if (!this.isRetailType) {
        delete payload.retailId;
        payload["merchantCategories"] =
          this.form.selectedMerchantCategories?.map((x) => {
            return x.id;
          });
        payload["merchantCities"] = this.form.selectedRegencies?.map((x) => {
          return x.id;
        });
      }

      if (this.state.isAutoGeneratedVoucher) {
        payload.autoGenerate = true;
        this.generateOptions.length = Number(this.generateOptions.length);
        this.generateOptions.count = Number(this.generateOptions.count);

        payload["generateOptions"] = this.generateOptions;
      }

      if (this.isEdited) {
        delete payload["file"];
        delete payload["id"];
      }

      const res = this.isEdited
        ? await this.$api.campaigns.voucher.update(
            campaignId,
            this.form.id,
            payload
          )
        : await this.$api.campaigns.voucher.upload(payload, this.isRetailType);

      if (res.success) {
        this.setSuccessAlert(
          this.isEdited ? "Voucher has been updated" : "Voucher has been added"
        );
        this.$emit("on:fetch");
      }

      if (!res.success) {
        this.setFailedAlert(res);
      }

      this.state.isLoading = false;

      this.onClearForm();
      this.onEmitClose();
    },

    onClearForm() {
      if (!this.isRetailType) {
        this.form.selectedMerchantCategories = [];
        this.form.selectedRegencies = [];
        this.form.searchMerchantCategories = "";
        this.form.searchRegencies = "";
      }
      this.form.retailId = null;
      this.form.date = "";
      this.form.time = {
        hh: "",
        mm: "",
        ss: "",
      };
      this.form.productId = {};
      this.form.expiredDate = null;
      this.form.limit = null;
      this.form.usageInstruction = null;
      this.form.file = null;
      this.$refs.form.resetValidation();
    },
  },

  watch: {
    async dialog(val) {
      if (val && this.item?.productId) {
        this.form = JSON.parse(JSON.stringify(this.item));

        this.form.date = this.$dayjs(this.form.expiredDate).format(
          "YYYY-MM-DD"
        );
        this.form.time = {
          HH: this.$dayjs(this.form.expiredDate).format("HH"),
          mm: this.$dayjs(this.form.expiredDate).format("mm"),
          ss: this.$dayjs(this.form.expiredDate).format("ss"),
        };
      }

      if ((await val) && !this.isEdited) {
        this.getMerchantCategories();
        this.getRegencies();
        this.onClearForm();
        this.$forceUpdate();
      }

      if (this.isEdited) {
        if (!this.isRetailType) {
          const tempForm = JSON.parse(JSON.stringify(this.item));

          this.form.selectedMerchantCategories =
            tempForm.merchantCategories?.map((x) => {
              return x.merchantCategory;
            });
          this.form.selectedRegencies = tempForm.merchantCities?.map((x) => {
            return x.merchantCity;
          });

          this.$forceUpdate();
        }

        this.$emit("fetch:partners", this.item.retail?.name);
      }
    },
    "form.limit"(val) {
      if (val) {
        this.form.limit = this.decimal(val);
      }
    },
  },
};
</script>

<style lang="scss" scoped>
.cropper-bg {
  background-image: none !important;
}

::v-deep .hide-input {
  .v-input__slot {
    display: none !important;
  }
  input {
    display: none !important;
  }
}
</style>
