name: CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Use Node.js 22.18.0
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"

      - name: 🧪 Confirm Node.js version
        run: node -v

      - name: 🔐 Inject .env
        continue-on-error: true
        run: |
          cat << EOF > .env
          ${{ secrets.ENV }}
          EOF

      - name: 📥 Install dependencies
        run: npm install

      - name: 🏗️ Build project
        run: |
          npm run build
          npm install --omit=dev

      - name: 📦 Archive production files
        run: |
          tar -czf build.tar.gz \
            .nuxt \
            node_modules \
            .env \
            static \
            nuxt.config.* \
            package.json \
            ecosystem.config.js || true

      - name: 🚀 Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./build.tar.gz
          target: /app/fe

      - name: 🔁 Restart PM2 on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app/fe

            echo "🧹 Cleaning old build..."
            pm2 stop fe || true
            rm -rf .nuxt node_modules build.tar.gz

            echo "📦 Extracting new build..."
            tar -xzf build.tar.gz

            echo "🚀 Restarting app with PM2..."
            pm2 start node_modules/nuxt/bin/nuxt.js -i max --name fe -- start
