name: CD

on:
  push:
    branches:
      - main

# on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.18.0"

      - name: Inject .env
        continue-on-error: true
        run: |
          cat << EOF > ./.env
          ${{ secrets.ENV }}
          EOF

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          npm install --omit=dev

      - name: Archive build files
        run: tar -czf build.tar.gz .nuxt node_modules .env static nuxt.config.js

      - name: Copy file to serevr
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./build.tar.gz
          target: /app/fe

      - name: Restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /app/fe
            tar -xzf build.tar.gz
            pm2 restart fe || pm2 start node_modules/nuxt/bin/nuxt.js -i max --name fe -- start
