name: Mirror to GitHub A

on:
  push:
    branches:
      - main # sesuaikan dengan branch Anda

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # Mencegah Git menggunakan token bot bawaan (GITHUB_TOKEN)

      - name: Push to GitHub A
        run: |
          git remote add target https://${{ secrets.PLATINUM_TOKEN }}@github.com/platinum-cineplex/fe-aegisbucks.git
          git push target main --force
